<?php
require_once "controller.php";
?>
<!DOCTYPE html>
<html lang="en">
<?= $Tag->createHead($title, $headerFiles) ?>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <?= $sideBar ?>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <nav class="nav navbar-nav">
                        <ul class=" navbar-right">
                            <li class="nav-item dropdown open" style="padding-left: 15px;">
                                <a href="javascript:;" class="user-profile" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                                    <?= $loggerName ?>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->

            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3><?= $pageName ?></h3>
                        </div>
                    </div>
                    <div class="clearfix"></div>

                    <div class="row">
                        <?= $responseOperation ?>
                        <div class="col-md-12 col-sm-12  ">
                            <div class="x_panel">
                                <div class="x_title">
                                    <h2>Create Staff</h2>
                                    <ul class="nav navbar-right panel_toolbox al_panel_toolbox">
                                        <li>
                                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    <form action='processor.php' method='post'>
                                        <input type='hidden' name='action' value='<?= $action ?>' />
                                        <?= $loginIdInput ?>
                                        <?= MyTag::getCSRFTokenInputTag() ?>
                                        <div class="row">
                                            <div class="col-4">
                                                <span class='d-block'>email *</span>
                                                <div class='form-group'>
                                                    <input value='<?= $thisStaffEmail ?>' type='email' name='email' class='form-control' required>
                                                </div>
                                            </div>
                                            <div class="col-4">
                                                <span class='d-block'>password</span>
                                                <div class='form-group'>
                                                    <input <?= $passwordDisabled ?> type='text' name='password' class='form-control' placeholder='generated by system if blank '>
                                                </div>
                                            </div>
                                            <div class="col-4">
                                                <span class='d-block'>staff type *</span>
                                                <div class='form-group row'>
                                                    <label class='form-check col-6'>
                                                        <input <?= $userTypeOneSelected ?> type='radio' class='form-check-input' name='staffType' id='optionsRadios1' value='<?= MyUsers::STAFF_TYPE[1] ?>' required>
                                                        <?= MyUsers::STAFF_TYPE[1] ?> <i class='input-helper'></i>
                                                    </label>
                                                    <label class='form-check col-6'>
                                                        <input <?= $userTypeZeroSelected ?> type='radio' class='form-check-input' name='staffType' id='optionsRadios1' value='<?= MyUsers::STAFF_TYPE[0] ?>'>
                                                        <?= MyUsers::STAFF_TYPE[0] ?> <i class='input-helper'></i>
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="col-4">
                                                <span class='d-block'>firstname *</span>
                                                <div class='form-group'>
                                                    <input value='<?= $firstname ?>' type='text' name='firstName' class='form-control' required>
                                                </div>
                                            </div>
                                            <div class="col-4">
                                                <span class='d-block'>middlename</span>
                                                <div class='form-group'>
                                                    <input value='<?= $middlename ?>' type='text' name='middleName' class='form-control'>
                                                </div>
                                            </div>
                                            <div class="col-4">
                                                <span class='d-block'>surname *</span>
                                                <div class='form-group'>
                                                    <input value='<?= $surname ?>' type='text' name='surName' class='form-control' required>
                                                </div>
                                            </div>
                                            <div class="col-4">
                                                <span class='d-block'>status *</span>
                                                <div class='form-group'>
                                                    <div class='form-group row'>
                                                        <label class='form-check col-6'>
                                                            <input <?= $activeSelected ?> type='radio' value='active' class='form-check-input' name='status' required>
                                                            active
                                                        </label>
                                                        <label class='form-check col-6'>
                                                            <input <?= $inActiveSelected ?> type='radio' value='inactive' class='form-check-input' name='status'>
                                                            inactive
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-4">
                                                <div class='form-group'>
                                                    <button type='submit' name='submit' class='btn btn-primary'><?= $btnCaption ?></button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12 col-sm-12  ">
                            <div class="x_panel">
                                <div class="x_title">
                                    <h2>List of Staffs on App</h2>
                                    <ul class="nav navbar-right panel_toolbox al_panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                                        </li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    <table id="datatable-buttons" class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Name</th>
                                                <th>Passport</th>
                                                <th>Contact</th>
                                                <th>Type</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?= $tr ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /page content -->

            <!-- footer content -->
            <?= $Tag->createFooterSlogan() ?>
            <!-- /footer content -->
        </div>
    </div>

    <?= $Tag->createFooterJS($footJs); ?>
</body>

</html>